### ISSUE TITLE
Dimensioni finestra e posizionamento

### ISSUE THREAD

**Issue by luigiferrari1001** [andreachiurla/LeggeGrandiNumeri#1]
Il fatto che la finestra cambi continuamente di dimensioni rende poco carino il programma. Inoltre dovresti fare in modo che compaia a centro schermo.

**Comment by andreachiurla** [comment]
Ora la finestra mantiene sempre le dimensioni che permettono di visualizzare tutti i contenuti e grazie a `frame.setLocationRelativeTo(null);` la finestra si apre al centro dello schermo.
